spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/buct?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: "030601"
  #若不存在表，项目启动时新建表
  sql:
    init:
      schema-locations: classpath*:buct.sql
      mode: always

#数据库配置
mybatis-plus:
  #设置别名
  type-aliases-package: com.buct.acmer.entity
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true
    #sql语句显示到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#swagger配置
config:
  swagger: true

#服务器启动端口配置
server:
  port: 8080
  servlet:
    context-path: /api

